  stages:
    - stage: windows
      displayName: 'Windows'
      pool:
        vmImage: 'windows-latest'
      jobs:
        - job: init
          displayName: init      
          steps:
          - script: dotnet restore Build.csproj
            workingDirectory: src
        - job: compile
          displayName: compile
          dependsOn: [ init ]
          steps:
          - script: dotnet flubu compile
            workingDirectory: src
        - job: test
          displayName: test
          dependsOn: [ compile ]
          steps:
          - script: dotnet flubu test
            workingDirectory: src
    - stage: linux_ubuntu
      displayName: 'Linux-Ubuntu'
      pool:
        vmImage: 'ubuntu-latest'
      jobs:
        - job: init
          displayName: init
          steps:
          - script: dotnet tool install --global FlubuCore.GlobalTool --version 5.1.8
        - job: compile
          displayName: compile
          dependsOn: [ init ]
          steps:
          - script: flubu compile.linux
        - job: test
          displayName: test
          dependsOn: [ compile ]
          steps:
          - script: flubu test.linux    
    - stage: macOS
      displayName: 'macOS'
      pool:
        vmImage: 'macOS-latest'
      jobs:
        - job: init
          displayName: init
          steps:
          - script: dotnet tool install --global FlubuCore.GlobalTool --version 5.1.8
        - job: compile
          displayName: compile
          dependsOn: [ init ]
          steps:
          - script: flubu compile.linux
        - job: test
          displayName: test
          dependsOn: [ compile ]
          steps:
          - script: flubu test.linux 

