variables:
  flubuVersion: 5.1.8

jobs:    

- job: Windows
  pool:
    vmImage: 'windows-latest'
  
  steps:

  - task: DotNetCoreInstaller@1
    displayName: install Sdk
    inputs:
      version: '3.1.100'      


  - task: DotNetCoreCLI@1
    displayName: initialize flubu
    inputs:
      command: custom
      custom: tool
      arguments: install -g FlubuCore.GlobalTool --version $(flubuVersion)
  - task: DotNetCoreCLI@1
    displayName: compile
    inputs:
      command: custom
      custom: flubu
      arguments: compile  

